---
abstract: 'utilities to be used with the Siebel srvrmgr program'
author:
  - 'Alceu Rodrigues de Freitas Junior <arfreitas@cpan.org>'
build_requires:
  Class::Data::Inheritable: 0.08
  Config::Tiny: 2.14
  Test::Class: 0.36
  Test::Exception: 0.27
  Test::Moose: 2.0801
  Test::Most: 0.25
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Siebel-Srvrmgr
no_index:
  directory:
    - t
    - inc
requires:
  FSA::Rules: 0.32
  Log::Log4perl: 1.41
  Moose: 2.0401
  Moose::Util::TypeConstraints: 2.0402
  MooseX::AbstractFactory: 0.004
  MooseX::FollowPBP: 0.05
  MooseX::Singleton: 0.27
  MooseX::Storage: 0.33
  YAML::Syck: 1.25
  namespace::autoclean: 0.13
  perl: 5.008009
resources:
  bugtracker: http://code.google.com/p/siebel-monitoring-tools/issues/list
  homepage: http://code.google.com/p/siebel-monitoring-tools/
  license: http://www.gnu.org/licenses/gpl.txt
  repository: http://code.google.com/p/siebel-monitoring-tools/source/browse/
version: 0.10
